config/routes.rb
Rails.application.routes.draw do
   # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    resources :items, only: [:index, :show]
    resources :customers, only: [:edit, :update]
    get 'customers/mypage' => 'customers#show'
     # 退会確認画面
    get  '/customers/check' => 'customers#check'
 # 論理削除用のルーティング
    patch  '/customers/withdraw' => 'customers#withdraw'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :create, :index, :show]
    post '/orders/check' => 'orders#check'
    get '/orders/completion' => 'orders#completion'
  end

  get '/admin' => 'admin/homes#top'
  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_one_attached :image

 def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  image.variant(resize_to_limit: [width, height]).processed
 end

   # 消費税を加えた商品価格
    def add_tax_price
        (self.price * 1.10).round
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<h2>商品編集</h2>
<%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>

<table>
  <tr>
    <td><span>商品画像</span><%= f.file_field :item_image, placeholder: "商品画像", accept: "image/*" %></td>
  </tr>

  <tr>
    <td><span>商品名</span><%= f.text_field :name %></td>
  </tr>

  <tr>
    <td><span>商品説明</span><%= f.text_area :introduction %></td>
  </tr>

  <tr>
    <td><span>税抜価格</span><%= f.text_field :price %></td>
  </tr>

  <tr>
    <td><%= f.submit '変更を保存' %></td>
  </tr>
</table>
<% end %>

app/views/admin/items/index.html.erb
<h3>商品一覧</h3>

<table>
  <thead>
    <tr>
      <th>商品ID</th> <th>商品名</th> <th>税抜き価格</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td><%= @items.item.id %></td>
      <td><%= @items.name %></td>
      <td><%= @items.price %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/items/new.html.erb
<h2>商品新規登録</h2>
<%= form_with model: @item, url: admin_items_path do |f| %>

<table>
  <tr>
    <td><span>商品画像</span><%= f.file_field :image, placeholder: "商品画像", accept: "image/*" %></td>
  </tr>

  <tr>
    <td><span>商品名</span><%= f.text_field :name %></td>
  </tr>

  <tr>
    <td><span>商品説明</span><%= f.text_area :introduction %></td>
  </tr>

  <tr>
    <td><span>税抜価格</span><%= f.text_field :price %></td>
  </tr>

  <tr>
    <td><%= f.submit '新規登録' %></td>
  </tr>
</table>
<% end %>

app/views/admin/items/show.html.erb
<h2>商品詳細</h2>

<div>
 <span>商品画像</span>
 <%= image_tag @item.get_image(200,200) %>
</div>

  <div>
   <span>商品名</span><%= @item.name %>
  </div>

  <div>
   <span>商品説明</span><%= @item.introduction %>
  </div>

  <div>
   <span>税込み価格(税抜価格)</span><%= @item.add_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円
  </div>

  <div>
   <%= link_to "編集する", edit_admin_item_path %>
  </div>