config/routes.rb
Rails.application.routes.draw do
   # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    resources :items, only: [:index, :show]
    resources :customers, only: [:edit, :update]
    get 'customers/mypage' => 'customers#show'
     # 退会確認画面
    get  '/customers/check' => 'customers#check'
 # 論理削除用のルーティング
    patch  '/customers/withdraw' => 'customers#withdraw'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :create, :index, :show]
    post '/orders/check' => 'orders#check'
    get '/orders/completion' => 'orders#completion'
  end

  get '/admin' => 'admin/homes#top'
  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customers = Customer.find(params[:id])
  end

  def edit
    @customers = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path(customer.id)
  end

  private
  def customer_params
    params.require(:customer).permit(:id, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h3><%= @customers.last_name %> <%= @customers.first_name %>さんの会員情報編集</h3>
<%= form_with model: @customers, url: admin_customer_path(@customers.id), method: :patch do |f| %>

<table>
  <tr>
    <td><span>会員ID</span><%= f.text_field :id %></td>
  </tr>

  <tr>
    <td><span>氏名</span><%= f.text_field :last_name %><%= f.text_field :first_name %></td>
  </tr>

  <tr>
    <td><span>フリガナ</span><%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %></td>
  </tr>

  <tr>
    <td><span>郵便番号</span><%= f.text_field :postal_code %></td>
  </tr>

  <tr>
    <td><span>住所</span><%= f.text_field :address,class: "selector" %></td>
  </tr>

  <tr>
    <td><span>電話番号</span><%= f.text_field :telephone_number %></td>
  </td>

   <tr>
    <td><span>メールアドレス</span><%= f.text_field :email %></td>
  </td>

  <tr>
    <td><%= f.submit '変更を保存' %></td>
  </tr>
</table>
<% end %>

app/views/admin/customers/index.html.erb
<h3>会員一覧</h3>

<table border="1" style="border-collapse: collapse">
  <thead>
    <tr>
      <th>会員ID</th> <th>氏名</th> <th>メールアドレス</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td><%= customer.last_name %> <%= customer.first_name %></td>
      <td><%= customer.email %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/customers/show.html.erb
<h3><%= @customers.last_name %> <%= @customers.first_name %>さんの会員詳細</h3>

<div>
  会員ID <%= @customers.id %>
</div>

<div>
  氏名 <%= @customers.last_name %> <%= @customers.first_name %>
</div>

<div>
  フリガナ <%= @customers.last_name_kana %> <%= @customers.first_name_kana %>
</div>

<div>
  郵便番号 <%= @customers.postal_code %>
</div>

<div>
  住所 <%= @customers.address %>
</div>

<div>
  電話番号 <%= @customers.telephone_number %>
</div>

<div>
  メールアドレス <%= @customers.email %>
</div>

<div>
  <%= link_to "編集する", edit_admin_customer_path %>
</div>

<div>
  <%= link_to "注文履歴一覧を見る", orders_path %>
</div